#单节点
#应用名称及验证账号
spring:
  application:
    name: eureka
  security:
    user:
      name: root
      password: root

server:
  port: 7901

eureka:
  instance:
    hostname: localhost



  client:

    #是否将自己注册到Eureka Server,默认为true，
    #如果是单节点纯当server，设置成false，表明该服务不会向eureka注册自己的信息
    #集群要设置成true
    register-with-eureka: false

    #是否从eureka server获取注册信息，如果是单节点，不需要同步其他节点数据，用false
    fetch-registry: false

    service-url:
      #设置服务注册中心的URL
      #集群的话，这个地址就是peer的地址
      defaultZone: http://root:root@localhost:7901/eureka/
  server:
    enable-self-preservation: true