#server:
#  port: 9100
#
#spring:
#  application:
#    name: gateway
#
##注册中心
#eureka:
#  client:
#    #设置服务注册中心的URL
#    service-url:
#      defaultZone: http://root:root@localhost:7901/eureka/
#  instance:
#    hostname: localhost
#    instance-id: ${spring.application.name}-${spring.cloud.client.ip-address}-${server.port}
#
#management:
#  endpoints:
#    web:
#      exposure:
#        include: "*"
#  endpoint:
#    health:
#      ##默认是never
#      show-details: ALWAYS
#      enabled: true
#    routes:
#      enabled: true
#
##指定负载均衡策略
#api-app:
#  ribbon:
#    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
